create table sys_role_menu
(
    role_id smallint unsigned not null comment '角色ID',
    menu_id smallint unsigned not null comment '菜单ID'
)
    comment '角色和菜单关联表';

INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 2);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 3);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 101);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 102);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 110);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 111);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 112);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 113);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 1);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 1);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 2);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 3);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 4);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 5);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 10);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 11);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 12);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 100);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 101);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 102);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 103);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 104);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 105);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 106);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 110);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 111);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 112);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 113);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 114);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 120);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 121);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 122);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 123);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 131);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 132);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 133);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 134);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 100);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (2, 1);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 4);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 120);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 121);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 122);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 123);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 2);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 100);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 101);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 102);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 103);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 104);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 105);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 106);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 3);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 110);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 111);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 112);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 113);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 114);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 4);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 120);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 121);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 122);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (3, 123);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (4, 9);
